# Generated by Django 3.0 on 2022-04-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_auto_20220406_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
